name: build-env
channels:
  - conda-forge
dependencies:
  - jupyterlab-language-pack-fr-FR
  - jupyterlite-xeus = 4.2.0
  - jupyterlite-pyodide-kernel
  - jupyter_server
  - ipywidgets
  - jupyterlab

#  - pip:
#    - jupyterlite-p5-kernel
  
