name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten # Mine for xeus-ocaml package
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - xeus-python
  - xeus-cpp
  - xeus-sqlite
  - xeus-javascript
  #- ipycanvas
  - xeus-ocaml = 0.0.2
