name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten # Mined from xeus-ocaml package
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - xeus-cpp
  - xeus-sqlite
  - xeus-javascript
  - ipycanvas
  - xeus-ocaml
