name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten # Mined from xeus-ocaml package
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - xeus-python
  - xeus-cpp
  - xeus-sqlite
  - xeus-javascript
  - ipycanvas
  - xeus-ocaml
