name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-javascript
  - xeus-lua
  - xeus-cpp
  - xeus-lua
  - xeus-sqlite
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - jupyterlite-ai
  - jupyterlite-core[translation]
  - pip:
      - ipycanvas
